version: '3'

services:
  soap_connector:
    build: .
    image: django-soap-connector:latest
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 127.0.0.1:8000"
    network_mode: "host"
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    container_name: soap_connector
    tty: true
